# 🗄️ CONFIGURACIÓN SIMPLE DE SUPABASE
# 
# Configuración básica para desarrollo local

project_id = "son1kverse"

[db]
port = 54322
major_version = 15

[db.pooler]
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
port = 54324

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_functions]
enabled = true
port = 54328

[analytics]
enabled = true
port = 54329
vector_port = 54330