# 🌌 SON1KVERSE FUNCTIONS - CONFIGURACIÓN SIMPLE
# 
# Configuración solo para funciones de Netlify

[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"
  QWEN_API_KEY = "sk-qwen-netlify-xxxxxxxxxxxxxxxx"
  QWEN_MODEL = "qwen2-7b-instruct"
  CACHE_SECRET = "netlify-cache-secret"
  SUPABASE_URL = "https://son1kverse.supabase.co"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
  SUNO_API_KEY = "Bearer REEMPLAZA_AQUI_TU_TOKEN"
  SUNO_BASE_URL = "https://ai.imgkits.com/suno"
  SUNO_POLLING_URL = "https://usa.imgkits.com/node-api/suno"
  MAX_REQUEST_SIZE = "10485760"
  REQUEST_TIMEOUT = "30000"
  CACHE_TTL = "300"

# 🌐 CONFIGURACIÓN DE REDIRECCIONES PARA FUNCIONES
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
