[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  QWEN_API_KEY = "sk-qwen-netlify-xxxxxxxxxxxxxxxx"
  QWEN_MODEL = "qwen2-7b-instruct"
  CACHE_SECRET = "netlify-cache-secret"
  SUPABASE_URL = "https://son1kverse.supabase.co"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
  SUNO_API_KEY = "Bearer REEMPLAZA_AQUI_TU_TOKEN"
  SUNO_BASE_URL = "https://ai.imgkits.com/suno"
  SUNO_POLLING_URL = "https://usa.imgkits.com/node-api/suno"
  MAX_REQUEST_SIZE = "10485760"
  REQUEST_TIMEOUT = "30000"
  CACHE_TTL = "300"

[functions]
  directory = "netlify/functions"

# 🌐 CONFIGURACIÓN DE REDIRECCIONES Y SUBDOMINIOS
[[redirects]]
  from = "https://son1kvers3.com/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "https://www.son1kvers3.com/*"
  to = "/index.html"
  status = 200
  force = true

# 🎵 GHOST STUDIO SUBDOMAIN
[[redirects]]
  from = "https://ghost-studio.son1kvers3.com/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-Ghost-Studio = "true"}

# 🚀 NOVA POST PILOT SUBDOMAIN
[[redirects]]
  from = "https://nova-post-pilot.son1kvers3.com/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-Nova-Post-Pilot = "true"}

# 🛡️ SANCTUARY SUBDOMAIN
[[redirects]]
  from = "https://sanctuary.son1kvers3.com/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-Sanctuary = "true"}

# 🎛️ THE GENERATOR SUBDOMAIN
[[redirects]]
  from = "https://the-generator.son1kvers3.com/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-The-Generator = "true"}

# 🤖 PIXEL SUBDOMAIN
[[redirects]]
  from = "https://pixel.son1kvers3.com/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-Pixel = "true"}

# 🎼 SUNO SUBDOMAIN
[[redirects]]
  from = "https://suno.son1kvers3.com/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-Suno = "true"}

# 📝 LETRAS SUBDOMAIN
[[redirects]]
  from = "https://letras.son1kvers3.com/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-Letras = "true"}

# 🧠 PROMPTS SUBDOMAIN
[[redirects]]
  from = "https://prompts.son1kvers3.com/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-Prompts = "true"}

# 🔒 CONFIGURACIÓN DE SEGURIDAD
[security]
  [security.headers]
    for = "/*"
    [security.headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://dashscope.aliyuncs.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://dashscope.aliyuncs.com https://son1kverse.supabase.co https://ai.imgkits.com https://usa.imgkits.com;"

# 📊 CONFIGURACIÓN DE ANALYTICS
[analytics]
  enabled = true